services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      source $HOME/.cargo/env
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: flask run
    pythonVersion: 3.10
    envVars:
      - key: CARGO_HOME
        value: /tmp/cargo
      - key: CARGO_TARGET_DIR
        value: /tmp/target
